//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_1_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criticos_Calificacion
    {
        public int IdCriticoCalificacion { get; set; }
        public int IdCritico { get; set; }
        public Nullable<int> IdPelicula { get; set; }
        public int Calificacion { get; set; }
    
        public virtual Criticos Criticos { get; set; }
        public virtual Criticos Criticos1 { get; set; }
        public virtual Peliculas Peliculas { get; set; }
        public virtual Peliculas Peliculas1 { get; set; }
    }
}
